version: '3.4'

services:
  videohub.webclient:
    image: videohub.webclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - "/app/node_modules"
      - ".:/app"
