version: '3.4'

services:
  videohub.api:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development-LAN
  videohub.identity:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development-LAN
  videohub.webclient:
    build:
      #dockerfile: ./Dockerfile-Development
      dockerfile: ./Dockerfile-Development_LAN
    environment:
      NODE_ENV: development