version: '3.4'

services:
  videohub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  videohub.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  videohub.webclient:
    environment:
      NODE_ENV: development

